---
platform: linux

# Does not support arm64
# image_resource:
#     type: registry-image
#     source:
#         repository: docker.io/concourse/oci-build-task

image_resource:
  type: registry-image
  source:
    repository: quay.io/podman/stable
    tag: latest

inputs:
- name: ghost-cloudflare-r2
- name: podman-base-image

outputs:
- name: podman-compose-image

run:
#   path: build
  path: ghost-cloudflare-r2/ci/scripts/build-podman-compose-image.sh
#   args: ["build", "-f", "ghost-cloudflare-r2/ci/images/podman-compose/Dockerfile", "-t", "podman-compose", "ghost-cloudflare-r2/ci/images/podman-compose"]
    # path: ls
#   args: ["-al"]
  # dir: ghost-cloudflare-r2
  # path: id
  # args: ["run", "--rm", "alpine", "echo", "hello"]
  # args: ["ps"]
