---
platform: linux
inputs:
- name: ghost-cloudflare-r2
- name: hurl-gh-release
- name: arch

# - name: minio-image
# - name: ghost-image
# - name: hurl-image
# - name: podman-compose-image
run:
  path: sh
  args:
    - -cx
    - |
      ls -al hurl-gh-release
      mkdir -p ~/.local/bin
      tar -xvzf hurl-gh-release/hurl-*-$(cat arch/arch)-unknown-linux-gnu.tar.gz -C ~/.local/bin --strip-components=2 hurl-6.0.0-$(cat arch/arch)-unknown-linux-gnu/bin/hurl
      ls -al ~/.local/bin
      ./ghost-cloudflare-r2/ci/scripts/run-integration-tests.sh