---
meta:
  gh-status-handlers: &gh-status-handlers
    on_success:
      put: gh-status
      inputs: [ghost-cloudflare-r2]
      params: {state: success}
    on_failure:
      put: gh-status
      inputs: [ghost-cloudflare-r2]
      params: {state: failure}
    on_error:
      put: gh-status
      inputs: [ghost-cloudflare-r2]
      params: {state: error}
    on_abort:
      put: gh-status
      inputs: [ghost-cloudflare-r2]
      params: {state: abort}

resource_types:
- name: cogito
  type: registry-image
  source:
    repository: 192.168.88.20:5000/cogito
    tag: 2024-12-20-arm64
    insecure: true

resources:
- name: gh-status
  type: cogito
  check_every: never
  source:
    owner: egeldenhuys
    repo: ghost-cloudflare-r2
    access_token: ((gh-status-access-token))

- name: ghost-cloudflare-r2
  type: git
  icon: github
  source:
    uri: https://github.com/egeldenhuys/ghost-cloudflare-r2.git
    branch: concourse-ci
# - name: minio-image
#   type: registry-image
#   icon: docker
#   source:
#     repository: 192.168.88.20:5001/minio/minio
#     tag: RELEASE.2024-12-18T13-15-44Z
# - name: ghost-image
#   type: registry-image
#   icon: docker
#   source:
#     repository: 192.168.88.20:5001/library/ghost
#     tag: 5.94
# - name: hurl-image
#   type: registry-image
#   icon: docker
#   source:
#     repository: 192.168.88.20:5002/orange-opensource/hurl
#     tag: 5.0.1
# - name: podman-base-image
#   type: registry-image
#   icon: docker
#   source:
#     repository: 192.168.88.20:5003/podman/stable
#     tag: latest
- name: podman-compose-image
  type: registry-image
  source:
    repository: 192.168.88.20:5000/podman-compose
    tag: latest

- name: hurl-gh-release
  type: github-release
  source:
    owner: Orange-OpenSource
    repository: hurl

# localhost:5000/oci-build-task:master-arm64

# - name: node-image
#   type: registry-image
#   source:
#     repository: node
#     tag: 20

jobs:
- name: npm-install-and-test
  <<: *gh-status-handlers
  plan:
    - get: ghost-cloudflare-r2
      trigger: true
    - put: gh-status
      inputs: [ghost-cloudflare-r2]
      params: {state: pending}
    - task: npm-install
      config:
        inputs:
          - name: ghost-cloudflare-r2
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: node
            tag: 20
        run:
          dir: ghost-cloudflare-r2
          path: sh
          args:
            - -cx
            - |
              npm install --include-dev
              npm run test

- name: build-podman-compose-image
  <<: *gh-status-handlers
  plan:
    - get: ghost-cloudflare-r2
      trigger: true
    - put: gh-status
      inputs: [ghost-cloudflare-r2]
      params: {state: pending}
    # - get: podman-base-image
    #   params: {format: oci}

    - task: build-image
      privileged: true
      file: ghost-cloudflare-r2/ci/tasks/build-podman-compose-image.yml

    - put: podman-compose-image
      params:
        image: image/image.tar

# - name: npm-install
#   <<: *gh-status-handlers
#   plan:
#   # - get: node-image
#   - get: ghost-cloudflare-r2
#     trigger: true
#   - put: gh-status
#     inputs: [ghost-cloudflare-r2]
#     params: {state: pending}
#   - task: npm-install
#     file: ghost-cloudflare-r2/ci/tasks/npm-install.yml

- name: integration-tests
  <<: *gh-status-handlers
  plan:
  - get: ghost-cloudflare-r2
    # trigger: true
  - put: gh-status
    inputs: [ghost-cloudflare-r2]
    params: {state: pending}
  # - get: minio-image
  #   params: {format: oci}
  # - get: ghost-image
  #   params: {format: oci}
  # - get: hurl-image
  #   params: {format: oci}
  - get: podman-compose-image
    passed: [build-podman-compose-image]
    trigger: true
  - task: get-worker-arch # TODO: is there a better way?
    image: podman-compose-image
    config:
      platform: linux
      outputs:
        - name: arch
      run:
        path: sh
        args:
          - -cx
          - |
            uname -m > arch/arch

  - load_var: arch
    file: arch/arch

  - get: hurl-gh-release
    params:
      version: { tag: 'v6.0.0' } # TODO: make var?
      globs: ["hurl-*-*-unknown-linux-gnu.tar.gz"]

  # - task: extract-hurl # TODO: is there a better way?
  #   image: podman-compose-image
  #   config:
  #     platform: linux
  #     inputs:
  #       - name: hurl-gh-release
  #     outputs:
  #       - name: hurl-gh-release-extracted
  #     run:
  #       path: sh
  #       args:
  #         - -cx
  #         - |
  #           tar -xvzf hurl-gh-release/hurl-*-((.:arch))-unknown-linux-gnu.tar.gz -C hurl-gh-release-extracted

  - task: integration-tests-task
    image: podman-compose-image
    privileged: true
    file: ghost-cloudflare-r2/ci/tasks/integration-tests.yml

  # - task: unit-tests
  #   image: node-image
  #   config:
  #     inputs:
  #     - name: repo
  #     - name: dependencies
  #       path: repo/node_modules
  #     platform: linux
  #     run:
  #       path: npm
  #       args: ["run", "test"]
  #       dir: repo